[personal]
first_name = "Alex"
last_name = "Davis"
profile_image = "portrait.jpg"
language = "en"
include_icons = true

[personal.info]
address = "Edinburgh, United Kingdom"
telephone = "+44 7446 163996"

[personal.info.email]
link = "mailto:8m3xlt@gmail.com"
label = "8m3xlt@gmail.com"

[personal.info.linkedin]
link = "https://www.linkedin.com/in/alexander-mark-davis/"
label = "linkedin.com/in/alexander-mark-davis/"

[personal.info.github]
link = "https://github.com/alexDavis28"
label = "github.com/alexDavis28"

[personal.info.homepage]
link = "https://alexdavis.tardis.ac/"
label = "alexdavis.tardis.ac"

[personal.icon]
address = "house"
telephone = "phone"
email = "envelope"
linkedin = "linkedin"
github = "github"
homepage = "globe"

[section.icon]
education = "graduation-cap"
experience = "briefcase"
languages = "language"
other_experience = "wrench"
personal = "brain"
profile = "id-card"
references = "users"
skills = "cogs"
projects = "code-fork"

# To change fill_color to white, replace value with "#ffffff"
[layout]
fill_color = "#f4f1eb"
paper_size = "a4"
accent_color = "#d4d2cc"
# deafult value is 71%
left_pane_width = "71%"

[layout.text]
font = "HK Grotesk"
size = "10pt"
cover_letter_size = "11pt"

[layout.text.color]
light = "#ededef"
medium = "#78787e"
dark = "#3c3c42"

[language.en]
subtitle = "Computer Science Student and Software Engineer"


[import]
path = "@preview/grotesk-cv:1.0.2"
fontawesome = "@preview/fontawesome:0.5.0"
